name: tencent_cloud_chat_plus
description: "A new Flutter package project."
version: 0.0.1
publish_to: none
homepage:

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.24.0"

platforms:
  android:
  ios:
  macos:
  web:
  windows:

dependencies:
  flutter:
    sdk: flutter

  tencent_cloud_chat_common: ^3.2.1
  tencent_cloud_chat_message: ^3.2.1
  tencent_cloud_chat_conversation: ^3.2.1
  tencent_cloud_chat_contact: ^3.2.1
  tencent_effect_flutter: 
    git:
      url: https://github.com/Tencent-RTC/TencentEffect_Flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

dependency_overrides:
  tencent_cloud_chat_sdk: 8.5.6864+2

  tencent_cloud_chat_common:
    git:
      url: https://github.com/kebdanimendhy/tencent_cloud_chat_common.git
      ref: dq
  tencent_cloud_chat_message:
    git:
      url: https://github.com/kebdanimendhy/tencent_cloud_chat_message.git
      ref: dq
  tencent_cloud_chat_conversation:
    git:
      url: https://github.com/kebdanimendhy/tencent_cloud_chat_conversation.git
      ref: dq
  tencent_cloud_chat_contact:
    git:
      url: https://github.com/kebdanimendhy/tencent_cloud_chat_contact.git
      ref: dq

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
